apiVersion: llo.aeros-project.eu/v1alpha1
kind: ServiceComponentK8s
metadata:
  labels:
    app.kubernetes.io/name: component-2-of-the-service-1
    app.kubernetes.io/instance: Service_1_Component_2
    app.kubernetes.io/part-of: Service_1
    app.kubernetes.io/managed-by: aeros-project.eu
    app.kubernetes.io/created-by: LowLevelOrchestrator_2
  name: service-1-mongo
spec:
  selectedIE:
    id: urn:ngsi-ld:InfrastructureElement:CloudFerro:2473d6a5a43b
    hostname: continuum-cluster-worker-1
  image: mongo:7.0.12
  ports:
    - number: 27017
      protocol: TCP
  # envVars:
  #   - key: MONGO_INITDB_ROOT_USERNAME
  #     value: test
  #   - key: MONGO_INITDB_ROOT_PASSWORD
  #     value: password
---
apiVersion: llo.aeros-project.eu/v1alpha1
kind: ServiceComponentK8s
metadata:
  labels:
    app.kubernetes.io/name: component-1-of-the-service-1
    app.kubernetes.io/instance: Service_1_Component_1
    app.kubernetes.io/part-of: Service_1
    app.kubernetes.io/managed-by: aeros-project.eu
    app.kubernetes.io/created-by: LowLevelOrchestrator_2
  name: service-1-orion-ld
spec:
  selectedIE:
    id: urn:ngsi-ld:InfrastructureElement:CloudFerro:4073c6a5a93b
    hostname: continuum-cluster-worker-2
  image: fiware/orion-ld:1.7.0
  ports:
    - number: 1026
      protocol: TCP
  cliArgs:
    - key: -brokerId
      value: test-broker
    - key: -dbhost
      value: service-1-mongo
    - key: -t
      value: 0-255
    - key: -logLevel
      value: DEBUG
    - key: -forwarding
    - key: -mongocOnly
    - key: -wip
      value: entityMaps,distSubs
    - key: -disableFileLog
    - key: -noArrayReduction
    - key: -subordinateEndpoint
      value: http://192.168.1.25:1026/ngsi-ld/ex/v1
    - key: -socketService
